
FROM node:18-alpine

WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm@latest

COPY veloris-site-template/package.json ./veloris-site-template/package.json
COPY veloris-site-template/pnpm-lock.yaml ./veloris-site-template/pnpm-lock.yaml

COPY veloris-dashboard/package.json ./veloris-dashboard/package.json
COPY veloris-dashboard/pnpm-lock.yaml ./veloris-dashboard/pnpm-lock.yaml

WORKDIR /app/veloris-site-template
RUN pnpm install

WORKDIR /app/veloris-dashboard
RUN pnpm install

WORKDIR /app

COPY veloris-site-template ./veloris-site-template
COPY veloris-dashboard ./veloris-dashboard
COPY nova ./nova

USER root

WORKDIR /veloris-site-template
EXPOSE 3000

CMD ["pnpm", "dev"]